theme:
permalink: /blog/:title

markdown: kramdown
kramdown:
    footnote_backlink: "[return]"

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
            show-date: false
            show-readtime: false
            show-header: true
            show-latest: true
            show-signature: false
            latex: false
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            show-date: true
            show-readtime: true
            show-header: true
            show-latest: true
            show-signature: true
            latex: false
