theme:
permalink: /blog/:title

# markdown: kramdown
# kramdown:
    # input:

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
            show-date: false
            show-readtime: false
            show-header: true
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            show-date: true
            show-readtime: true
            show-header: true
